#!/bin/bash

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

install_docker() {
   curl -fsSL get.docker.com | sh
   sudo usermod -aG docker $USER
}

install_k3s() {
  curl -sfL https://get.k3s.io | sh 
}

install_k3d() {
  curl -s https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash
}

main() {
    if ! command_exists docker; then
        install_docker
    fi

    install_k3s
    install_k3d

    echo "please relogin for the configuration to take affect."
}

main
