#!/bin/bash

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

install_docker() {
   curl -fsSL get.docker.com | sh
   sudo usermod -aG docker $USER
}

install_k3s() {
  curl -sfL https://get.k3s.io | sh 
  sudo apt install -y k3d
}

main() {
    if ! command_exists docker; then
        install_docker
    fi

    install_k3s
}

main
