#!/bin/bash

pyenv() {
    curl_install https://pyenv.run
    pyenvrc=~/.pyenvrc
    tee $pyenvrc <<-'EOF'
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
EOF
    export PATH="$HOME/.pyenv/bin:$PATH"
    echo "source $pyenvrc" >> $profile

    # install python3
    _python3
    _python_formatter
}

_python_formatter() {
    install['apt']="python3-pip"
    install_pack ${install["$pm"]}

    $gosu pip3 install black isort
    echo "===> python formatter are installed successfully."
}

_python3() {
    remove_pack python3 || :
    setup_pyenv

    ver=3.7.2
    PY3_PREFIX=$HOME/.pyenv/versions/$ver
    if [ ! -d "$PY3_PREFIX" ];then
        # install dependency
        install['yum']="ncurses-devel zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel"
        install['apt']="make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl"
        install_pack ${install["$pm"]}
        pyenv install $ver
        PY3_PREFIX=`pyenv prefix $ver`
    fi
    pyenv global $ver
    eval "$(pyenv init -)"
    export PY3_CONFIG=`$PY3_PREFIX/bin/python-config --configdir`
    echo "===> python $ver is installed successfully."
}
