" Vim Settings {
    " UI { 
        " allow plugins by file type (required for plugins!)
        filetype plugin on
        filetype indent on
        
        " syntax highlight on
        syntax on
        colorscheme desert

        " Fix vim takes a very long time to start up. https://stackoverflow.com/a/17719528
        set clipboard=exclude:.*

        set nocompatible                " no vi-compatible
        set linespace=0                 " No extra spaces between rows
        set number                      " Line numbers on
        set showmatch                   " Show matching brackets/parenthesis
        set incsearch                   " Find as you type search
        set hlsearch                    " Highlight search terms
        set winminheight=0              " Windows can be 0 line high
        set ignorecase                  " Case insensitive search
        set smartcase                   " Case sensitive when uc present
        set wildmenu                    " Show list instead of just completing

        " With a map leader it's possible to do extra key combinations
        let mapleader = ","
        let g:mapleader = ","
    " }

    " Formatting {

        set nowrap                      " Do not wrap long lines
        set autoindent                  " Indent at the same level of the previous line
        " C++, Groovy, Java, JavaScript, Perl, Python and Tcl indent. 
        "autocmd FileType cpp,groovy,java,javascript,perl,python,tcl,sh 
        "            \ setl sw=4 sts=4 et
        set shiftwidth=4                " Use indents of 4 spaces
        set expandtab                   " Tabs are spaces, not tabs
        set tabstop=4                   " An indentation every four columns
        set softtabstop=4               " Let backspace delete indent
        set nojoinspaces                " Prevents inserting two spaces after punctuation on a join (J)
        set splitright                  " Puts new vsplit windows to the right of the current
        set splitbelow                  " Puts new split windows to the bottom of the current
        "set matchpairs+=<:>             " Match, to be used with %
        set pastetoggle=<F12>           " pastetoggle (sane indentation on pastes)

        " groovy.vim support
        au BufNewFile,BufRead *.groovy setf groovy
        au BufNewFile,BufRead Jenkinsfile setf groovy

    " }
    
    " Tab {
        " Useful mappings for managing tabs
        map <leader>tn :tabnew<cr>
        map <leader>to :tabonly<cr>
        map <leader>tc :tabclose<cr>
        map <leader>tm :tabmove

        " Opens a new tab with the current buffer's path
        " Super useful when editing files in the same directory
        map <leader>te :tabedit <c-r>=expand("%:p:h")<cr>/
    " }
    " VIMDIFF {
	if &diff
		map gs :call IwhiteToggle()<CR>
		function! IwhiteToggle()
			if &diffopt =~ 'iwhite'
				set diffopt-=iwhite
			else
				set diffopt+=iwhite
			endif
		endfunction
	endif 
    " }

    " Key Mappings {
        " -- git command on current file
		fun! GitCommand(command)
		  silent! !clear
		  exec "!git " . a:command . " %"
		endfun
		" -- git diff for current file
		map <leader>d :call GitCommand("diff") <CR>
		" -- git log for current file
		map <leader>l :call GitCommand("log -p") <CR>
		" -- git blame for current file
		map <leader>b :call GitCommand("blame") <CR>

        " Wrapped lines goes down/up to next row, rather than next line in file.
        noremap j gj
        noremap k gk

        " Allow saving of files as sudo when I forgot to start vim using sudo."
        cmap w!! w !sudo tee > /dev/null %

        " Map 'save' to ctrl-s, and first find out if you can configure your
        " xterm to pass Ctrl+S through to the application.
        :nmap <c-s> :w<CR>
        :imap <c-s> <Esc>:w<CR>a

        " Add quote around the word
        :nnoremap <Leader>q" ciw""<Esc>P
        :nnoremap <Leader>q' ciw''<Esc>P
        :nnoremap <Leader>qd daW"=substitute(@@,"'\\\|\"","","g")<CR>P"'")"'"

        " Format groovy indent (just like javascript indent)
        map <leader>gf :setf javascript<cr>gg=G:setf groovy<cr>

    " }
    " Misc {
        " Return to last edit position when opening files (You want this!)
        autocmd BufReadPost *
             \ if line("'\"") > 0 && line("'\"") <= line("$") |
             \   exe "normal! g`\"" |
             \ endif
        " Remember info about open buffers on close
        set viminfo^=%
    " }
" }

" using ace-profile/utility/vim_pack to install vim plugin for vim8
" Plugin Settings {
	" Ale {
		let g:ale_linters = {}
		let g:ale_linters.python = ['flake8']
		let g:ale_linters.javascript = ['eslint']
		let g:ale_linters.sh = ['shellcheck']

		let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace']}
		let g:ale_fixers.python = ['black', 'isort']
		let g:ale_fixers.javascript = ['prettier']
		let g:ale_fixers.scss = ['stylelint']
		let g:ale_fixers.css = ['stylelint']
		let g:ale_fixers.go = ['gofmt']

		" auto fix on save
		let g:ale_fix_on_save = 1
		" let g:ale_lint_on_save = 1
	" }
    
    " Completor {
      " pip install jedi first
    " }

    " Nerdcommenter {
    "   Ctrl + / to to toggle comments like in vscode
        map <C-_> <plug>NERDCommenterToggle  
    " }
    
    " NerdTree {
       " toggle nerdtree display
       map <F3> :NERDTreeToggle<CR>
       " open nerdtree with the current file selected
       nmap ,t :NERDTreeFind<CR>
       " don;t show these file types
       let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
    " }

    " Ctrlp {
        " tags (symbols) in current file finder mapping
        nmap ,g :CtrlPBufTag<CR>
        " tags (symbols) in all files finder mapping
        nmap ,G :CtrlPBufTagAll<CR>
        " general code finder in all files mapping
        nmap ,f :CtrlPLine<CR>
        " recent files finder mapping
        nmap ,m :CtrlPMRUFiles<CR>
        " commands finder mapping
        nmap ,c :CtrlPCmdPalette<CR>
        " to be able to call CtrlP with default search text
        function! CtrlPWithSearchText(search_text, ctrlp_command_end)
            execute ':CtrlP' . a:ctrlp_command_end
            call feedkeys(a:search_text)
        endfunction
        " same as previous mappings, but calling with current word as default text
        nmap ,wg :call CtrlPWithSearchText(expand('<cword>'), 'BufTag')<CR>
        nmap ,wG :call CtrlPWithSearchText(expand('<cword>'), 'BufTagAll')<CR>
        nmap ,wf :call CtrlPWithSearchText(expand('<cword>'), 'Line')<CR>
        nmap ,we :call CtrlPWithSearchText(expand('<cword>'), '')<CR>
        nmap ,pe :call CtrlPWithSearchText(expand('<cfile>'), '')<CR>
        nmap ,wm :call CtrlPWithSearchText(expand('<cword>'), 'MRUFiles')<CR>
        nmap ,wc :call CtrlPWithSearchText(expand('<cword>'), 'CmdPalette')<CR>
        " don't change working directory
        let g:ctrlp_working_path_mode = 0
        " ignore these files and folders on file finder
        let g:ctrlp_custom_ignore = {
          \ 'dir':  '\v[\/](\.git|\.hg|\.svn|node_modules)$',
          \ 'file': '\.pyc$\|\.pyo$',
          \ } 
    " }
    
    " Tagbar {
         " toggle tagbar display
         map <F4> :TagbarToggle<CR>
         " autofocus on tagbar open
         let g:tagbar_autofocus = 1
    " }
" }
