#!/usr/bin/env bash

source $HOME/.ace_profile_env
INSTALLATION_PATH=$PROFILE_PATH/installer
source $INSTALLATION_PATH/global.sh

# Plugin lists for different platforms
LINUX_PLUGS="\
     tpope/vim-fugitive \
     mhinz/vim-signify \
     SirVer/ultisnips \
     acefei/vim-snippets\
     Yggdroot/LeaderF \
     dense-analysis/ale \
     jiangmiao/auto-pairs \
     scrooloose/nerdcommenter \
     "

NON_LINUX_PLUGS="\
     tpope/vim-fugitive \
     mhinz/vim-signify \
     jiangmiao/auto-pairs \
     scrooloose/nerdcommenter \
     "
#==================== End Plugin List =========================


# Create new folder in ~/.vim/pack that contains a start folder and cd into it.
#
# Arguments:
#   package_group, a string folder name to create and change into.
#
# Examples:
#   set_group syntax-highlighting
#
set_group() {
  package_group=$1
  path="$HOME/.vim/pack/$package_group/start"
  mkdir -p "$path"
  cd "$path" || exit
}

# Clone or update a git repo in the current directory.
#
# Arguments:
#   repo_url, a URL to the git repo.
#
# Examples:
#   package https://github.com/tpope/vim-endwise.git
#
package() {
  repo_url=$1
  expected_repo=$(basename "$repo_url" .git)
  if [ -d "$expected_repo" ]; then
    cd "$expected_repo" || exit
    result=$(git pull --force)
    echo "vim-plugin $expected_repo: $result"
  else
    git clone -q "$repo_url" --depth 1
    echo "vim-plugin $expected_repo: Done..."
  fi
}

# Install vim plugin in parallel
install_plugins() {
    # Determine which plugins to install based on platform
    if is_win || is_mac; then
        install_group "non-linux" "$NON_LINUX_PLUGS"
    else
        install_group "linux" "$LINUX_PLUGS"
    fi
}

install_group() {
    local group_name=$1
    local plugins=$2
    
    set_group "$group_name"
    for plug in $plugins; do
        package https://github.com/${plug}.git &
    done
    wait
}

finish() {
    # remove the plugins unused
    cd $HOME/.vim/pack
    # given above installation is running in parallel, so it should be finish in 5 min, all of dir touched out of 5 min should be removed.
    old_plugs=$(find ./*/*/*/.git -prune -mmin +5 -print | sed "s/\/.git//")
    if [ -n "$old_plugs" ]; then
        echo
        echo "Removing old plugins:"
        echo $old_plugs | xargs rm -rf
    fi

    # copy _vimrc to ~/.vimrc
    ln -sf $vimrcs/_vimrc $vimrc
}
trap finish EXIT

install_plugins
