#!/bin/bash
set -eu
 
# get checked list when source <path>/multiselect <list>
CHECKED_OPTIONS=()

multiselect() {
    options=($@)
     
    # default select all
    select_all='y'
    mask='*'
    msg=''

    _menu() {
        echo "Avaliable options:"
        for i in ${!options[@]}; do
            [[ "$select_all" ]] && choices[i]="$mask"
            printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
        done
        select_all=''
        [[ "$msg" ]] && echo "$msg"; :
    }

    _is_num() {
        echo "$1" | grep -qP "^\d+$"
    }
     
    # Prompt
    prompt="Input num to toggle an option (ENTER to exit): "
    while _menu && read -rp "$prompt" num && [[ "$num" ]]; do
        _is_num "$num" && (( num > 0 && num <= ${#options[@]} )) \
            || { msg="Invalid option: $num"; continue; }

        ((num--)); msg="${options[num]} was ${choices[num]:+un}checked"

        [ -n "${choices[num]}" ] && choices[num]="" || choices[num]="$mask"
    done
     
    # Final result
    printf "You selected"; msg=" nothing"
    for i in "${!options[@]}"; do
        [ -n "${choices[i]}" ] && { printf " %s" "${options[i]}"; CHECKED_OPTIONS+=(${options[i]}) msg=""; }
    done
    echo "$msg"
}

multiselect $@
